server:
  port: 8080

spring:
  application:
    name: smartcare-backend
  data:
    mongodb:
      uri: mongodb+srv://it24101143_db_user:VvRctiWxxlrD1vsX@cluster0.4lwp61h.mongodb.net/smartcare_db?appName=Cluster0
      auto-index-creation: true

smartcare:
  jwt:
    secret: SmartCareSecretKeyForJwtAuthenticationSystemWith256BitsMinimumLength1234567890
    expiration-ms: 86400000 # 24 hours
  ai:
    service-url: http://localhost:8000
